# Generated by Django 4.2.30 on 2026-06-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_add_sala_to_agenda'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('sala__isnull', False)), fields=('sala', 'fecha', 'hora_inicio'), name='unique_sala_fecha_hora'),
        ),
    ]
