# Generated by Django 4.2.30 on 2026-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_unique_sala_fecha_hora'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='unique_sala_fecha_hora',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('sala', 'fecha', 'hora_inicio'), name='unique_sala_fecha_hora'),
        ),
    ]
