# Generated by Django 4.2.30 on 2026-06-12 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_unique_sala_fecha_hora_v2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha', 'hora_inicio'), name='unique_medico_fecha_hora'),
        ),
    ]
